name: Ci

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-14-xlarge
    timeout-minutes: 8

    steps:
    - uses: actions/checkout@v2  # Utilisez v2 pour plus de stabilité

    - name: Install fastlane
      run: |
        gem install fastlane

    - name: Install dependencies
      run: |
        bundle install

    - name: Run fastlane to manage signing and build
      run: |
        fastlane match development  # Cela va gérer automatiquement les certificats et profils
        xcodebuild clean build test \
          -project EPCollaboratif.xcodeproj \
          -scheme "EPCollaboratif" \
          -sdk iphonesimulator \
          -destination "platform=iOS Simulator,name=iPhone 14 Pro Max,OS=16.2" \
          ONLY_ACTIVE_ARCH=YES
