<<<<<<< HEAD
name: Ci_

=======
name: iOS Build and Test
>>>>>>> screencast
on:
    pull_request:
    branches: [ main ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build-and-test"
    build-and-test:
    # The type of runner that the job will run on
    runs-on: macos-14-xlarge
    
    timeout-minutes: 8
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
<<<<<<< HEAD
    # Étape pour vérifier le code source
    - uses: actions/checkout@v2

    # Étape pour installer fastlane
    - name: Install fastlane
      run: gem install fastlane

    # Étape pour installer Bundler
    - name: Install Bundler
      run: gem install bundler

    # Étape pour installer les dépendances via Bundler (utilisant Gemfile)
    - name: Install dependencies
      run: bundle install

    # Étape pour sélectionner la version Xcode (vérifiez qu'elle est installée sur l'instance)
    - name: Select Xcode version
      run: sudo xcode-select -switch /Applications/Xcode_15.4.app

    # Étape pour vérifier la version d'Xcode
=======
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
    
    - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_15.4.app
    
>>>>>>> screencast
    - name: Xcode version
        run: /usr/bin/xcodebuild -version
    
    - name: Build and Test
<<<<<<< HEAD
      run: |
        fastlane match development  # Cela va gérer automatiquement les certificats et profils
        xcodebuild clean build test \
          -project EPCollaboratif.xcodeproj \
          -scheme "EPCollaboratif" \
          -sdk iphonesimulator \
          -destination "platform=iOS Simulator,name=iPhone 14 Pro Max,OS=16.2" \
          ONLY_ACTIVE_ARCH=YES
=======
        run: xcodebuild clean build test -project EPCollaboratif.xcodeproj -scheme "EPCollaboratif" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14 Pro Max,OS=16.2" ONLY_ACTIVE_ARCH=YES
>>>>>>> screencast
