name: iOS Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Mise à jour vers v3

      - name: Build and Test
        uses: sersoft-gmbh/xcodebuild-action@v3.2.0
        with:
          project: EPCollaboratif.xcodeproj
          scheme: EPCollaboratif
          destination: 'platform=iOS Simulator,name=iPhone 14'
          action: test
          result-bundle-path: 'TestResults/TestResults.xcresult'

      - name: Process Test Results
        uses: kishikawakatsumi/xcresulttool@v2  # Mise à jour si v2 est disponible
        with:
          path: TestResults/TestResults.xcresult
        if: success() || failure()

      - name: Upload Test Results
        uses: actions/upload-artifact@v4  # Ajout de l'action v4 pour le téléchargement des résultats (si nécessaire)
        with:
          name: TestResults
          path: TestResults/TestResults.xcresult
