name: Ci_

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-14-xlarge
    timeout-minutes: 8

    steps:
    # Étape pour vérifier le code source
    - uses: actions/checkout@v2

<<<<<<< HEAD
    - name: Install fastlane
      run: |
        gem install fastlane

    - name: Install dependencies
      run: |
        bundle install

    - name: Run fastlane to manage signing and build
=======
    # Étape pour installer Bundler
    - name: Install Bundler
      run: gem install bundler

    # Étape pour installer les dépendances via Bundler (utilisant Gemfile)
    - name: Install dependencies
      run: bundle install

    # Étape pour sélectionner la version Xcode (vérifiez qu'elle est installée sur l'instance)
    - name: Select Xcode version
      run: sudo xcode-select -switch /Applications/Xcode_15.4.app

    # Étape pour vérifier la version d'Xcode
    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    # Étape pour construire et tester l'application
    - name: Build and Test
>>>>>>> main
      run: |
        fastlane match development  # Cela va gérer automatiquement les certificats et profils
        xcodebuild clean build test \
          -project EPCollaboratif.xcodeproj \
          -scheme "EPCollaboratif" \
          -sdk iphonesimulator \
          -destination "platform=iOS Simulator,name=iPhone 14 Pro Max,OS=16.2" \
          ONLY_ACTIVE_ARCH=YES
